version: "3.9"

services:

  mongo-ci:
    image: mongo:6
    container_name: mongo-ci
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - ci-network

  backend-ci:
    image: node:20
    container_name: backend-ci
    working_dir: /app
    volumes:
      - ./Basic Ecomerce:/app
    environment:
      - PORT=5050
      MONGO_URI_DOCKER=mongodb://admin:password@mongo-ci:27017/ecommerce?authSource=admin
    command: sh -c "npm install && npm start"
    ports:
      - "5050:5050"
    depends_on:
      - mongo-ci
    networks:
      - ci-network

  frontend-ci:
    image: node:20
    container_name: frontend-ci
    working_dir: /app
    volumes:
      - ./frontend/ToyStore:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5175:5173"
    depends_on:
      - backend-ci
    networks:
      - ci-network

  selenium-tests:
    build:
      context: ./tests  
    container_name: selenium-tests
    depends_on:
      - frontend-ci
    networks:
      - ci-network

volumes:
  mongo_data:

networks:
  ci-network:
    driver: bridge
